### ISSUE TITLE
the bash_it recipe's default custom plugins are not easily overridable

### ISSUE THREAD

**Issue by codeword** [pivotal-sprout/sprout-base#11]
the bash_it recipe looks for custom plugins in the attributes node `bash_it -> custom_plugins` and defines a default set as

```
custom_plugins:
  sprout-base:
    - pluginA
    - pluginB
```

but chef only overrides defaults at the leaf nodes, so in soloist

```
custom_plugins:
  my-plugins:
    - pluginC
```

results in pluginA, pluginB and pluginC all being installed. 

If a user doesn't want pluginA or pluginB installed they would need to set sprout-base to an empty array.

```
custom_plugins:
  my-plugins:
    - my-plugin
  sprout-base: []
```

which is very surprising behavior.

**Comment by aramprice** [comment]
Going to archive this repo, closing.
