### ISSUE TITLE
Is there any reason not to use the `git` resource to install `bash_it` in-place

### ISSUE THREAD

**Issue by aramprice** [pivotal-sprout/sprout-base#14]
Instead of cloning it to the cache dir and then `rsync`-ing it into `~/.bash_it`?

See: [/recipes/bash_it.rb:3-18](https://github.com/pivotal-sprout/sprout-base/blob/master/recipes/bash_it.rb#L3-L18)

``` ruby
git "#{Chef::Config[:file_cache_path]}/bash_it" do
  repository node['bash_it']['repository']
  revision bash_it_version
  destination "#{Chef::Config[:file_cache_path]}/bash_it"
  action :sync
end

directory node['bash_it']['dir'] do
  owner node['sprout']['user']
  mode '0777'
end

execute "Copying bash-it's .git to #{node['bash_it']['dir']}" do
  command "rsync -axSH #{Chef::Config[:file_cache_path]}/bash_it/ #{node['bash_it']['dir']}"
  user node['sprout']['user']
end
```

ping @cunnie

**Comment by cunnie** [comment]
IIRC, we were probably worried that it wouldn't do a git pull if there were any modifications; however, I think our fears may have been unfounded and the git resource is a good way to go.

**Comment by aramprice** [comment]
@cunnie thanks for the background.
