### ISSUE TITLE
Remove "user_owns_usr_local" recipe (Homebrew no longer needs this)

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-base#16]
Homebrew was updated to not need the user to own `/usr/local`. We can remove this recipe.

**Comment by aramprice** [comment]
Do we still need to ensure that `/usr/local` has been created or does homebrew handle that?

**Comment by TildeWill** [comment]
It also fails hard on OXS 10.13 because you can no longer `chown` that directory
https://github.com/Homebrew/brew/issues/3228

Maybe a rescue if it is unsuccessful?

**Comment by TildeWill** [comment]
Sounds good to me. Want a pull request, or should I just hold off?

**Comment by aramprice** [comment]
As far as I know home-brew handles this now. If you're up for making a PR I think just deleting the recipe is good.
