### ISSUE TITLE
`git_prompt_info` no longer used in `bobby`

### ISSUE THREAD

**Issue by utako** [pivotal-sprout/sprout-base#17]
The change in the bobby theme discussed [here](https://github.com/Bash-it/bash-it/pull/804) requires that we make a change. We can just rename this function or just make our own custom theme to avoid having to make these changes in the future. 

I propose this `prompt_command`:

```
PS1="\n$(battery_char) $(clock_prompt) 🐌  ${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(git_prompt_info) ${green}→${reset_color} "

```

**Comment by aramprice** [comment]
I think that we should override [git_prompt_vars](https://github.com/Bash-it/bash-it/blob/255c66dd43a25533f47bfadd3727928a3eab14e8/themes/base.theme.bash#L127) or better yet add `git-duet` support to bash_it directly.

**Comment by aramprice** [comment]
Going to archive this repo, closing.
