### ISSUE TITLE
sprout-base::bash_it should not overwrite .bash_profile

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [pivotal-sprout/sprout-base#19]
If a user runs the `sprout-base::bash_it` recipe to install and configure bash_it, the recipe blows away any configuration that already exists in their `~/.bash_profile` when setting up bash-it's `export`s.

If the user has an existing `~/.bash_profile`, the recipe should add the bash-it exports to that file instead of overwriting the file with them. Ideally, the exports would be prepended, which can be handled by ~~piping the output of a multiline echo to `cat`.~~ somebody better at Bash than me 😔 

appending to bash_profile is simple enough though:

```sh
$ echo 'export PATH="/usr/local/bin:$PATH" 

# Path to the bash it configuration
export BASH_IT="$HOME/.bash_it"

# Lock and Load a custom theme file
export BASH_IT_THEME="bobby"

# Load Bash It
source $BASH_IT/bash_it.sh
' >> ~/.bash_profile
```

~~This will error if `~/.bash_profile` doesn't exist already, but that's mitigated simply enough with a quick `touch` first.~~

**Comment by aramprice** [comment]
Going to archive this repo, closing.
