### ISSUE TITLE
`homebrew` recipe should not depend on `bash_it` recipe

### ISSUE THREAD

**Issue by hjhart** [pivotal-sprout/sprout-base#2]
Is there any reasoning behind why there is an explicit recipe inclusion for bash_it that I'm overlooking?

```
include_recipe "sprout-base::bash_it"
```

@hiremaga

**Comment by rbaumbach** [comment]
+1, I'd be great if bash_it wasn't required as I use my own bash configurations.

**Comment by wendorf** [comment]
The homebrew recipe was removed as of [this commit](https://github.com/pivotal-sprout/sprout-base/commit/34c16145f82ab9d4772d831d1e897303d48d9670).
